Update fail.yml

diff --git a/.github/workflows/fail.yml b/.github/workflows/fail.yml
--- a/.github/workflows/fail.yml
+++ b/.github/workflows/fail.yml
@@ -21,7 +21,7 @@ jobs:
         run: echo "Waiting for 5 minutes before failing..."
       # - name: Sleep for 5 minutes
         # run: sleep 300  # 300 seconds = 5 minutes
-      - name: Fail intentionally
-        run: |
-          echo "Now failing the workflow after waiting."
-          exit 1
+      # - name: Fail intentionally
+      #   run: |
+      #     echo "Now failing the workflow after waiting."
+      #     exit 1
